packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - core-js-pure
  - cypress
  - sharp

catalogMode: "strict"

catalog:
  "next": "^15.3.0"
  react: "^19.1.0"
  react-dom: "^19.1.0"
  "@cypress/react": "^9.0.1"
  "@eslint/js": "^9.26.0"
  "@next/eslint-plugin-next": "^15.3.0"
  "@testing-library/jest-dom": "^6.6.3"
  "@testing-library/react": "^16.1.0"
  "@turbo/gen": "^2.5.0"
  "@types/node": "^22.15.3"
  "@types/react": "19.1.12"
  "@types/react-dom": "19.1.9"
  "@vitejs/plugin-react": "^5.0.0"
  "cypress": "^15.0.0"
  eslint: "^9.26.0"
  "eslint-config-prettier": "^10.1.1"
  "eslint-plugin-only-warn": "^1.1.0"
  "eslint-plugin-react": "^7.37.4"
  "eslint-plugin-react-hooks": "^5.2.0"
  "eslint-plugin-turbo": "^2.5.0"
  "globals": "^16.0.0"
  husky: "^9.1.7"
  lint-staged: "^16.1.5"
  "jsdom": "^26.0.0"
  prettier: "^3.5.3"
  "start-server-and-test": "^2.0.13"
  turbo: "^2.5.6"
  typescript: "5.9.2"
  "typescript-eslint": "^8.31.0"
  "vitest": "^3.0.0"
