packages:
  - apps/*
  - packages/*

catalog:
  "@cypress/react": ^9.0.1
  "@eslint/eslintrc": ^3
  "@eslint/js": 9.36.0
  "@libsql/client": ^0.15.15
  "@next/eslint-plugin-next": ^15.3.0
  "@tailwindcss/postcss": ^4
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.1.0
  "@turbo/gen": ^2.5.0
  "@types/better-sqlite3": ^7.6.13
  "@types/node": ^22.15.3
  "@types/pg": ^8.15.5
  "@types/react": 19.1.13
  "@types/react-dom": 19.1.9
  "@vitejs/plugin-react": ^5.0.0
  better-sqlite3: ^12.2.0
  cypress: ^15.0.0
  dotenv: 17.2.2
  drizzle-kit: 0.31.4
  drizzle-orm: 0.44.5
  eslint: 9.36.0
  eslint-config-next: ^15.5.3
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.0
  globals: ^16.0.0
  husky: ^9.1.7
  jsdom: ^27.0.0
  lint-staged: ^16.1.6
  next: ^15.3.0
  pg: ^8.16.3
  prettier: ^3.6.2
  react: ^19.1.0
  react-dom: ^19.1.0
  start-server-and-test: ^2.0.13
  tailwindcss: ^4
  tsx: ^4.20.5
  turbo: ^2.5.8
  typescript: 5.9.2
  typescript-eslint: ^8.31.0
  vitest: ^3.0.0
  zod: ^4.1.11

catalogMode: strict

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - better-sqlite3
  - core-js-pure
  - cypress
  - esbuild
  - sharp
  - unrs-resolver
