packages:
  - apps/*
  - packages/*

catalog:
  "@cypress/react": ^9.0.1
  "@eslint/eslintrc": ^3
  "@eslint/js": 9.39.2
  "@libsql/client": 0.17.0
  "@next/eslint-plugin-next": ^15.3.0
  "@radix-ui/react-dropdown-menu": 2.1.16
  "@radix-ui/react-label": 2.1.8
  "@radix-ui/react-separator": 1.1.8
  "@radix-ui/react-slot": 1.2.4
  "@radix-ui/react-tooltip": ^1.2.8
  "@tailwindcss/postcss": ^4
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.1.0
  "@turbo/gen": ^2.5.0
  "@types/better-sqlite3": ^7.6.13
  "@types/node": 24.10.3
  "@types/pg": ^8.15.5
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@vitejs/plugin-react": ^5.0.0
  autoprefixer: ^10.4.21
  babel-plugin-react-compiler: ^1.0.0
  better-sqlite3: 12.5.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cypress: ^15.0.0
  dotenv: 17.2.3
  drizzle-kit: 0.31.8
  drizzle-orm: 0.45.1
  eslint: 9.39.2
  eslint-config-next: ^16.0.1
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.0
  globals: ^17.0.0
  husky: ^9.1.7
  jsdom: ^27.0.0
  lint-staged: ^16.2.7
  lucide-react: 0.562.0
  next: ^16.0.1
  next-themes: 0.4.6
  pg: ^8.16.3
  postcss: ^8.5.6
  prettier: ^3.7.4
  react: ^19.2.0
  react-dom: ^19.2.0
  start-server-and-test: ^2.0.13
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.17
  tailwindcss-animate: ^1.0.7
  tsx: 4.21.0
  turbo: ^2.6.3
  tw-animate-css: ^1.4.0
  typescript: 5.9.3
  typescript-eslint: ^8.31.0
  vitest: ^4.0.0
  zod: ^4.1.11

catalogMode: strict

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - better-sqlite3
  - core-js-pure
  - cypress
  - esbuild
  - sharp
  - unrs-resolver
