name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "22.15.1"
  TURBO_CACHE_DIR: .turbo
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  # TURBO_TEAM: your-team-slug   # uncomment if using a Vercel Team

jobs:
  quality: # lint + format:check + typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get pnpm version from package.json
        id: pnpmv
        run: echo "PNPM_VERSION=$(jq -r '.packageManager' package.json | cut -d'@' -f2)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Restore Turbo cache (fallback to remote cache)
        id: turbo-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/turbo.json','**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/turbo.json','**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-turbo-

      - name: Validate renovate.json
        run: npx --yes --package renovate -- renovate-config-validator renovate.json

      - name: Run quality checks
        run: pnpm turbo run lint format:check check:types --cache-dir $TURBO_CACHE_DIR --continue

      - name: Save Turbo cache
        uses: actions/cache/save@v4
        if: steps.turbo-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/turbo.json','**/pnpm-lock.yaml') }}-${{ github.sha }}

  unit:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get pnpm version from package.json
        id: pnpmv
        run: echo "PNPM_VERSION=$(jq -r '.packageManager' package.json | cut -d'@' -f2)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Restore Turbo cache
        id: turbo-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/turbo.json','**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/turbo.json','**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-turbo-

      - name: Run unit tests
        run: pnpm turbo run test --cache-dir $TURBO_CACHE_DIR --continue

      - name: Save Turbo cache
        uses: actions/cache/save@v4
        if: steps.turbo-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/turbo.json','**/pnpm-lock.yaml') }}-${{ github.sha }}

  browser-tests:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get pnpm version from package.json
        id: pnpmv
        run: echo "PNPM_VERSION=$(jq -r '.packageManager' package.json | cut -d'@' -f2)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Restore Cypress binary cache
        id: cypress-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Ensure Cypress binary is installed
        working-directory: apps/web
        env:
          CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
        run: pnpm cypress install --force

      - name: Restore Turbo cache
        id: turbo-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/turbo.json','**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/turbo.json','**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-turbo-

      - name: Run browser-based tests
        run: pnpm turbo run test:browser-based --cache-dir $TURBO_CACHE_DIR --continue

      - name: Save Cypress binary cache
        if: steps.cypress-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Save Turbo cache
        uses: actions/cache/save@v4
        if: steps.turbo-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/turbo.json','**/pnpm-lock.yaml') }}-${{ github.sha }}

  build:
    needs: [quality, unit, browser-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get pnpm version from package.json
        id: pnpmv
        run: echo "PNPM_VERSION=$(jq -r '.packageManager' package.json | cut -d'@' -f2)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Restore Turbo cache
        id: turbo-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/turbo.json','**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/turbo.json','**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-turbo-

      - name: Build
        run: pnpm turbo run build --cache-dir $TURBO_CACHE_DIR --continue

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            apps/**/dist
            packages/**/dist
            !**/node_modules/**

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy
        run: ./scripts/deploy.sh dist
